export const UPDATE_UNPACKED_ITEMS_FILTER = 'UPDATE_UNPACKED_ITEMS_FILTER';
export const UPDATE_PACKED_ITEMS_FILTER = 'UPDATE_PACKED_ITEMS_FILTER';

export const UPDATE_NEW_ITEM_VALUE = 'UPDATE_NEW_ITEM_VALUE';

export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_ITEM = 'TOGGLE_ITEM';
export const MARK_ALL_AS_UNPACKED = 'MARK_ALL_AS_UNPACKED';
